spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grad_box_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.material.manaement.model.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: graduation-project-platform-secret-key-2024-2025-2026-premium-ultra-secure-key-512bit #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

logging:
  level:
    com.material.manaement: debug